
owner: callmeurpapa 
repo: uptime 

sites:
  - name: SIBUR
    url: https://sibur.ru/ru/
  - name: TAIF
    url: http://taif.ru
  - name: B2b
    url: https://b2b.sibur.ru
  - name: B2B-rni
    url: https://b2b-rni.sibur.ru
  - name: career
    url: https://career.sibur.ru
  - name: Nipigas
    url: http://nipigas.ru
  - name: Amur GCC
    url: http://amur-gcc.ru
  - name: YUG
    url: http://sibur-yug.ru
  - name: Magazine
    url: https://magazine.sibur.ru
  - name: Digest
    url: https://digest.sibur.ru
  - name: Digital
    url: https://sibur.digital
  - name: SIBUR-2
    url: http://sibur.ru
    
status-website:
  baseUrl: uptime
  logoUrl: https://www.sibur.ru/local/templates/main/assets/images/Fav-ru.jpg
  name: Upptime
  introTitle: "Мониторинг времени работы и состояния вебсайтов"
  introMessage: ¯\_(ツ)_/¯ 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

#workflowSchedule:
#  graphs: "0 */6 * * *"
#  responseTime: "10 */6 * * *"
#  staticSite: "20 */6 * * *"
#  summary: "30 */6 * * *"
#  updateTemplate: "0 0 * * *"
#  updates: "40 */6 * * *"
#  uptime: "*/5 * * * *"
