repo: upptime # The name of this repository

sites:
  - name: SIBUR
    url: https://wwww.sibur.ru
  - name: TAIF
    url: https://taif.ru
  - name: B2b
    url: https://b2b.sibur.ru
  - name: B2B-rni
    url: https://b2b-rni.sibur.ru

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
@@ -29,3 +29,15 @@ status-website:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page is [created]($REPO) @2022-07-01 by [51Sec](www.51sec.org), powered by [Upptime](https://upptime.js.org)

workflowSchedule:
  graphs: "0 */6 * * *"
  responseTime: "10 */6 * * *"
  staticSite: "20 */6 * * *"
  summary: "30 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "40 */6 * * *"
  uptime: "*/5 * * * *"
